### ISSUE TITLE
Further reduce the Appendix

### ISSUE THREAD

**Issue by sridharangirish91** [SpencerDawkins/net-collab-rqmts#105]
If the document is focused on Host-to-Network signaling, can we remove the following from appendix, which are not focused on host-network signaling?

1. NRLP
2. Assited Offloading
3. Redundant Functions and Classification Complications
4. Metadata Scope
5. Application Interface (Since we are focusing only within the same UDP 4-tuple, we don't need to mention about multiple applications).

We can also remove the corresponding requirements to keep the document more focused and shorter.

The extended use case would just contain media streaming extended (which the majority of traffic).

Thoughts?

**Comment by boucadair** [comment]
Agree. A first cut is integrated into the active PR: https://github.com/SpencerDawkins/net-collab-rqmts/pull/104/files#diff-c99ba6e278dc52e98eec3ca28e94e28e7e38efc47f03816e9cf679ce8315f591
