### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by danwing** [SpencerDawkins/net-collab-rqmts#26]
Along the lines of [SCONE's API](https://datatracker.ietf.org/doc/draft-eddy-sconepro-api/), do we want to say anything about the API needs?

I noticed their API document conflates a single API with "receiving data over the QUIC flow", which of course isn't necessary considering that [ICMP errors are sent to (connected) UDP sockets](https://mailarchive.ietf.org/arch/msg/behave/ZXQ4xLYrqPB3CxLMnRNmzApK0oU/), and those are different flows. So, there could be a single API which does all your QUIC things and, under the covers, does a separate signaling channel with the ISP(s) router(s), exposing the information to the application without the application needing to do heavy lifting. We might call that a 'library' or I suppose in 2024 we would have to call that a 'framework' or 'wrapper' or some-such.

**Comment by boucadair** [comment]
This can be mentioned as part of a new OPS section, e.g., "Exposure Handling".

The local exposure (OS API) can be mentioned, e.g., next to REQ-SIGNAL-EXPOSURE-FAIRNESS in #25.

**Comment by sridharangirish91** [comment]
I thought this would be more of a metadata specific aspect but we could list the "framework" as a requirement in the signaling. In that case, do we need to have API(s) for the client/host to network signaling as well? Include that in the framework as well?
