### ISSUE TITLE
Comment on "Priority within a Flow (Intra-Flow)"

### ISSUE THREAD

**Issue by tireddy2** [SpencerDawkins/net-collab-rqmts#3]
Without a signaling in place between a receiving host and its network, remote peers are able to mark every packet of a flow as important, causing much the same problem as the previous use-case. Eventually, when all packets of every flow are marked as important, there is no differentiation between packets within a flow, rendering the network unable to improve reactive policy decisions.

Comment> The above text is not clear to me. How will the signaling mechanism between a receiving host and its network prevent a misbehaving remote peer from marking every packet of a flow as import ? 

The signalling requirement to detect and block such a misuse is not discussed in this section.

**Comment by danwing** [comment]
Worse, the text in the I-D is discussing *inter* flow priority.  That is, priority between flows, where every flow says "I am important".  But we have agreed to constrain the I-D to discuss only priority of packets within a single flow (that is, within a 5-tuple).  So, *intra* flow priority.

The value of signaling from client to the ISP's router is in getting agreement to honor the intra-flow priority values, and getting agreement how they are signaled from server-to-client -- can they be signaled with UDP Options?  Can they be signaled with DSCP?  Can they be signaled with QUIC Connection IDs?  Can they be signaled with RTP/SRTP SSRC?  The ISP router knows what it supports, the client (from discussions with the server) knows what the server supports.  They can find a mutually-agreed-upon signaling mechanism.

**Comment by tireddy2** [comment]
Yes, I updated the metadata scope section in the pull request to clarify that inter flow priority is out of scope by adding the following text: 

The metadata can be used by the network to prioritize traffic within a single 5-tuple connection and metadata cannot be leveraged for prioritization between different flows.

**Comment by boucadair** [comment]
> Worse, the text in the I-D is discussing _inter_ flow priority. That is, priority between flows, where every flow says "I am important".

We need to put in bold that the focus is intra-flow or flows of the same user. I updated the abstract to have the warning early in the document. Otherwise, we will be opening lot of noise.

**Comment by tireddy2** [comment]
> > Worse, the text in the I-D is discussing _inter_ flow priority. That is, priority between flows, where every flow says "I am important".
> 
> We need to put in bold that the focus is intra-flow or flows of the same user. I updated the abstract to have the warning early in the document. Otherwise, we will be opening lot of noise.

Prioritizing flows from the same host is also error-prone because the network cannot distinguish between legitimate and malicious flows. For example, a poorly written application might request the highest priority for its flows, which could be unjustified. Additionally, it is challenging to identify whether the traffic belongs to a single user or multiple users, such as in tethering scenarios. Therefore, I propose focusing solely on "intra-flow" prioritization. Both WebRTC and QUIC, multiplex multiple streams on the same 5-tuple.
