### ISSUE TITLE
Network to host section required?

### ISSUE THREAD

**Issue by sridharangirish91** [SpencerDawkins/net-collab-rqmts#37]
In https://datatracker.ietf.org/doc/html/draft-joras-sconepro-video-opt-requirements-00, the requirements seem to have a network to host part, which we haven't focused much on here (some of it is in https://github.com/boucadair/draft-xxx-ac-rate-policy-discovery/blob/main/draft-brw-sconepro-rate-policy-discovery.md). Do we need to add a section iterating the requirements for network to host signaling to have a more holistic picture?

**Comment by danwing** [comment]
Network should be able to tell host that previously-signaled conditions have changed (e.g., throughput has declined or increased).  Is more needed?

**Comment by danwing** [comment]
The section titled "Network-Host Metadata" (currently Section 5.2) only mentions Assisted Offload.  It doesn't mention available bandwidth.  That's a major miss!  The abstract even mentions bandwidth!!  Oops.

I'll add text if Sridharan is already asleep.

**Comment by boucadair** [comment]
Yes, agree. We need to have some text about this.
