### ISSUE TITLE
REQ-FRAME-MIDDLE

### ISSUE THREAD

**Issue by tireddy2** [SpencerDawkins/net-collab-rqmts#49]
Regarding the requirement REQ-FRAME-MIDDLE, What will the network element do by identifying middle of media frame ?

**Comment by danwing** [comment]
Know it is related to an associated REQ-FRAME-FIRST or -FRAME-LAST, and either send all of them or none of them.

If there is a better way to express this in requirements, go for it!

**Comment by tireddy2** [comment]
I understand the need for first and last frame but don't get the use of middle frame to be conveyed to the network.

**Comment by danwing** [comment]
I suppose what is necessary is “identify all packets belonging to the same media frame, so they can receive equal drop/forward treatment” might be the actual requirement??-dOn Jun 9, 2024, at 12:43 AM, Tirumaleswar Reddy ***@***.***> wrote:﻿
I understand the need for first and last frame but don't get the use of middle frame to be conveyed to the network.

**Comment by sridharangirish91** [comment]
If that's the case, just a media identifier should suffice right? We may not need a start, middle and end if all the 3 are meant to do the same. Will the network do anything different knowing media has started and ended specifically?

**Comment by tireddy2** [comment]
> I suppose what is necessary is “identify all packets belonging to the same media frame, so they can receive equal drop/forward treatment” might be the actual requirement?

Yes, that makes sense. we can get rid of start, middle and end frames requirements.

**Comment by danwing** [comment]
Submitted pull request https://github.com/SpencerDawkins/net-collab-rqmts/pull/53 to resolve this one
