### ISSUE TITLE
Burst Indication

### ISSUE THREAD

**Issue by tireddy2** [SpencerDawkins/net-collab-rqmts#6]
The server may also signal end of burst that provides information for the radio to go into sleep mode (Connected Mode Discontinuous Reception, C-DRX) if there is no paging message.

Comment> The requirement seems specific to 3GPP, can you add a reference to the document ?

**Comment by danwing** [comment]
Supposedly 3gpp got the idea from 802.11ba, according to https://ieeexplore.ieee.org/document/9686039.  So should cite both 3gpp spec as well as 802.11ba, https://standards.ieee.org/ieee/802.11ba/6896/
