### ISSUE TITLE
Abuse and Constraints 

### ISSUE THREAD

**Issue by tireddy2** [SpencerDawkins/net-collab-rqmts#7]
## Abuse and Constraints {#abuse}

It is important that not every flow be prioritized; otherwise, the network devolves into the best-effort network that existed prior to metadata signaling. It is a requirement that mechanisms exist to prevent this occurrence.

Such a mechanism might be simple, for example, a cellular network might allow one flow from a subscriber to declare itself as important; other flows with that subscriber are denied attempts to prioritize themselves.

Comment> The network cannot identify whether the prioritized flow is legitimate or malicious. It has no info to detect malicious flows, if several flows mark themselves as important. I don't think prioritizing a flow over others is in the scope of this draft.

**Comment by danwing** [comment]
The text quoted from the I-D ("It is important that not every flow be prioritized") is referring to *inter* flow priority, which is out of scope for the I-D.  Remove.
