### ISSUE TITLE
introduction is really long

### ISSUE THREAD

**Issue by danwing** [SpencerDawkins/net-collab-rqmts#88]
Introduction would benefit from a diet, or at least breaking into sub-sections.  Some documents have a separate background section but existing text does not seem to talk a lot about existing systems.  Hm.  Suggestions?

**Comment by John-Kaippallimalil** [comment]
I agree that section 1 (Intro) would benefit from breaking into 2 sections.
How about a short Introduction (section 1) that provides an overview of what's in the document, and 
A new section that follows ( -- something like "Rationale for Per-packet Metadata") which would contain the gist of what is currently in the intro but reduced in length (as much as possible).
Highlighting "per-packet metadata" in a section heading may also help bringing attention to "per-packet (vs. per-flow).

**Comment by danwing** [comment]
See how #91 feels -- I moved one new paragraph up, and slammed all the rest of the existing introduction into a new section 1.1, _Rational for Per-Packet Metadata_.
